Repository leorodney/server, pull requests merged in 2023-03, with the labels that each got.

#3 The base structure build #2
  .gitignore
  README.md
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.cjs
  client/src/components/App.jsx
  client/src/main.jsx
  client/src/styles/App.css
  client/src/styles/index.css
  client/tailwind.config.cjs
  client/vite.config.js
  server/database/connect.js
  server/models/Prompt.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: good first issue, build

#14 setup CI boilerplate envirment
  client/package-lock.json
  client/package.json
  server/models/Prompt.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: duplicate, enhancement, build, setup

#13 NodeJS Continues Integration (CI)
  .github/workflows/node.js.yml
  server/models/Prompt.js
  server/package-lock.json
  server/package.json
Labels: documentation, duplicate, enhancement, setup

#16 Setup security CodeQL
  .github/workflows/codeql.yml
Labels: duplicate, enhancement, setup, CI, security

#18 add assets and readme file
  README.md
  assets/FrontCover.png
Labels: documentation, duplicate, setup

#21 Frontend Codebase Migration
  .gitignore
  README.md
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/assets/leorodney-fav-b.png
  client/src/assets/leorodney-fav-w.png
  client/src/assets/leorodney.png
  client/src/assets/logo-b.png
  client/src/assets/logo-w.png
  client/src/assets/placeholder.png
  client/src/components/App.jsx
  client/src/main.jsx
  client/src/main.tsx
  client/src/pages/Community.tsx
  client/src/pages/Demo.tsx
  client/src/pages/Production.tsx
  client/src/router.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: duplicate, enhancement, build, setup

#22 dark and light favicon.
  client/index.html
Labels: enhancement, setup

#25 backend codebase migration
  client/package-lock.json
  client/package.json
  server/database/connect.js
  server/database/connect.ts
  server/models/Prompt.ts
  server/package-lock.json
  server/package.json
  server/server.ts
  server/src/@types/Prompt.d.ts
  server/src/@types/connect.d.ts
  server/tsconfig.json
Labels: duplicate, enhancement, build, setup

#28 Community page
  client/index.html
  client/src/assets/HeroBG.png
  client/src/components/Hero.tsx
  client/src/components/ShowCases.tsx
  client/src/pages/Demo.tsx
  client/src/router.tsx
Labels: build, setup
