Repository leorodney/server, pull requests merged in 2023-05, with the labels that each got.

#107 update packages
  auth/package-lock.json
  getway/package-lock.json
  production/package-lock.json
  promptify/package-lock.json
  prompts/package-lock.json
Labels: dependencies

#108 Docker microservices
  auth/Dockerfile
  docker-compose.yml
  getway/Dockerfile
  production/Dockerfile
  promptify/Dockerfile
  prompts/Dockerfile
Labels: config, refactor

#110 Auto Assign Workflow
  .github/workflows/auto-assign.yml
Labels: CI, CD, config
